navigation:
  - text: About
    url: /about.html
  - text: Projects
    url: /projects.html
  - text: Contact
    url: /contact.html

blubb: ['eins','zwei','drei']

future: false

exclude: ['README.md','Gemfile','Gemfile.lock','Assetfile','tmp','assets']